AWSTemplateFormatVersion: 2010-09-09
Description: Template for creating IAM Role to switch from other AWS Account
Parameters:
  TrustedAWSAccountId:
    AllowedPattern: "^[0-9]*$"
    Type: String
    Default: ""
    Description: Trusted AWS Account ID
  IAMUserName:
    Type: String
    Description: IAM User name that allows permission switch from Trusted AWS Account
  IAMRoleName:
    Type: String
    Description: IAM Role name to create this AWS Account
  MaxSessionDuration:
    Description: The maximum session duration (in seconds)
    Type: Number
    Default: 43200
    MinValue: 3600
    MaxValue: 43200
Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                !Join [
                  "",
                  [
                    "arn:aws:iam::",
                    !Ref TrustedAWSAccountId,
                    ":user/",
                    !Ref IAMUserName,
                  ],
                ]
            Action:
              - sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: "true"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      MaxSessionDuration: Integer
      Path: "/"
      RoleName:
        Ref: IAMRoleName
Outputs:
  IAMRoleArn:
    Value: !GetAtt [IAMRole, Arn]
  LinkForSwitchRole:
    Value:
      !Join [
        "",
        [
          "https://signin.aws.amazon.com/switchrole?roleName=",
          !Ref IAMUserName,
          "&account=",
          !Ref AWS::AccountId,
        ],
      ]
